### ISSUE TITLE
kratjes.net

### ISSUE THREAD

**Issue by joszuijderwijk** [jordy-u/zeerspecifiekevragen.nl#1]
Vul onderstaande informatie in:
**Website URL:** https://kratjes.net
**Waarom moet deze toegevoegd worden?:** Misschien niet specifiek genoeg, maar niet geschoten is altijd mis hè.
**Website voldoet aan onderstaande voorwaarden:** Ja

Let op: De website moet voldoen aan de onderstaande eisen. De website moet...:
* ...een **specifieke** vraag beantwoorden
  * Hoe specifieker hoe beter. 
* ...**grappig** zijn
  * Websites zoals watismijnipadres.nl beantwoorden een specifieke vraag, maar zijn niet bepaald leuk of 'doorstuur-waardig'.
* ...**beknopt** zijn
  * Het moet geen grote informatie-pagina zijn met veel tekst. Het antwoord op de vraag moet kort en duidelijk zijn.
* ...**Nederlands** zijn
  * Er zijn enorm veel leuke websites die aan bovenstaande eisen voldoen. Echter wil ik dat zeerspecifiekevragen.nl een  samenstelling is van websites die in ons mooie kikkerlandje zijn gemaakt.

**Comment by jordy-u** [comment]
Hey @iovidius. Bedankt voor je suggestie. Wat gaaf dat je die bierklok zelfs fysiek hebt gemaakt.

De domeinnaam is niet als vraag geformuleerd. Echter beantwoord het wel een specifieke vraag (namelijk: "Welke kratjes zijn in de aanbieding?") en ik vind het een leuke om aan de site toe te voegen.

Je ziet hem binnenkort verschijnen, zodra deze issue opgelost is.

**Comment by joszuijderwijk** [comment]
Thanks man! Mooi rijtje om tussen te staan, haha ;)

**Comment by jordy-u** [comment]
No problem. 👍
Hij staat erop.
